lib/registration_web/router.ex
defmodule RegistrationWeb.Router do
  use RegistrationWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  #plug RegistrationWeb.Plugs.LoadStudent
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend do
    plug RegistrationWeb.Plugs.LoadStudent
  end

  scope "/", RegistrationWeb do
    pipe_through [:browser, :frontend]


    get "/signup", SignupController, :new
    post "/signup", SignupController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create


  end



  scope "/", RegistrationWeb do
   pipe_through [:browser, :frontend, RegistrationWeb.Plugs.AuthenticateStudent]
   get "/", PageController, :index
   resources "/courses", CourseController
   get "/course/student", CourseController, :view
   get "/logout", SessionController, :delete
   resources "/papers", PaperController

  end
  # Other scopes may use custom stacks.
  # scope "/api", RegistrationWeb do
  #   pipe_through :api
  # end
end

lib/registration_web/controllers/course_controller.ex
defmodule RegistrationWeb.CourseController do
  use RegistrationWeb, :controller
  alias Registration.Management.Student
  alias Registration.Management
  alias Registration.Management.Course
  alias Registration.Repo

  def index(conn, _params) do
  #  student =conn.assigns.student
  current_student = conn.assigns.current_student
    course = Management.list_dept_courses(current_student.department)
    render(conn, "index.html", course: course )
  end


    def create(conn, %{ "course" => course_params}) do
      student = conn.assigns.current_student
      course_id = Map.get(course_params, "course_id")
      case Management.add_course(course_id, student) do
        {:ok,_} ->
          conn
          |> put_flash(:info, "Course Added successfully.")
          |> redirect(to: Routes.course_path(conn, :view))

        {:error, %Ecto.Changeset{} = changeset} ->
          conn
          |> put_flash(:info, "Memo already  sent to this user.")
          |> redirect(to: Routes.course_path(conn, :index))
       #   render conn, "index.html"
      end
end

def view(conn, _params) do
  current_student = conn.assigns.current_student
student = Management.get_student!(current_student.id)
render(conn, "view.html", student: student)
end

def delete(conn, %{"id" => id}) do
  course = Management.get_course!(id)
  {:ok, _course} = Management.delete_course(course)
  conn
  |> put_flash(:info, "Course Removed.")
  |> redirect(to: Routes.course_path(conn, :index))
end
end

lib/registration_web/controllers/page_controller.ex
defmodule RegistrationWeb.PageController do
  use RegistrationWeb, :controller

  def index(conn, _params) do
    student = conn.assigns.current_student
    render(conn, "index.html", student: student)
  end
end

lib/registration_web/controllers/paper_controller.ex
defmodule RegistrationWeb.PaperController do
  use RegistrationWeb, :controller

  alias Registration.Submission
  alias Registration.Submission.Paper

  def index(conn, _params) do
    student = conn.assigns.current_student
    papers = Submission.list_student_papers(student )
    render(conn, "index.html", papers: papers)
  end

  def new(conn, _params) do
    student = conn.assigns.current_student
   changeset = Submission.build_student_paper(student)
    #changeset = Submission.change_paper(%Paper{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"paper" => paper_params}) do
    student = conn.assigns.current_student
    case Submission.create_student_paper(student, paper_params) do
      {:ok, paper} ->
        conn
        |> put_flash(:info, "Paper created successfully.")
        |> redirect(to: Routes.paper_path(conn, :show, paper))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    student = conn.assigns.current_student
    paper = Submission.get_student_paper!(student, id)
    render(conn, "show.html", paper: paper)
  end

  
end

lib/registration_web/controllers/session_controller.ex
defmodule RegistrationWeb.SessionController do
  use RegistrationWeb, :controller
  alias  Registration.Management.Student
  alias  Registration.Management



def new(conn, _params) do

  render conn, "new.html"
end


def create(conn, %{"session" => session_params}) do
case Management.get_student_by_credentials(session_params) do
:error ->
conn
|> put_flash(:error, "Invalid mat number/password combo")
student ->
  conn
  |> assign(:current_student, student)
  |> put_session(:student_id, student.id)
  #|> configure_session(renew: true)
  |> put_flash(:info, "Login successful")
  |> redirect(to: Routes.page_path(conn, :index))
end
end

def delete(conn, _) do
  clear_session(conn)
  |> put_flash(:info, "You have been logged out")
  |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/registration_web/controllers/signup_controller.ex
defmodule RegistrationWeb.SignupController do
  use RegistrationWeb, :controller
  alias  Registration.Management.Student
  alias  Registration.Management

  def new(conn, _params) do
    changeset = Management.build_student()
    render(conn, "new.html", changeset: changeset)
  end


  def create(conn, %{"student" => student_params}) do
    case Management.create_student(student_params) do
      {:ok, student} ->
      conn
      |> put_flash(:info, "Registration successful")
      |> redirect(to: Routes.page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
  end
end
end

lib/registration_web/views/course_view.ex
defmodule RegistrationWeb.CourseView do
  use RegistrationWeb, :view
  alias  Registration.Management.Student
  alias  Registration.Management.Course
  alias  Registration.Management.Request

  def render("index.json", %{ course_params: course_params})
  do

  %{
  message: "Course Added"

  }
  end


end

lib/registration_web/views/error_view.ex
defmodule RegistrationWeb.ErrorView do
  use RegistrationWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/registration_web/views/layout_view.ex
defmodule RegistrationWeb.LayoutView do
  use RegistrationWeb, :view
end

lib/registration_web/views/page_view.ex
defmodule RegistrationWeb.PageView do
  use RegistrationWeb, :view
end

lib/registration_web/views/paper_view.ex
defmodule RegistrationWeb.PaperView do
  use RegistrationWeb, :view
end

lib/registration_web/views/session_view.ex
defmodule RegistrationWeb.SessionView do
  use RegistrationWeb, :view
end

lib/registration_web/views/signup_view.ex
defmodule RegistrationWeb.SignupView do
  use RegistrationWeb, :view
end

lib/registration_web/templates/course/index.html.eex
<div class="column main-pane">


  <div class= "content-pane">
<div class="reg-text">Please select from the following courses in your department for this term </div>


 <table class="table table-striped table-hover trans-table column col-11 col-mx-auto">
      <thead>
        <tr>
          <th class="code">Code</th>
          <th class="title">Title</th>
          <th class="credits">Credits</th>
           <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <%= for course <- @course do %>
         <tr>
         <%= form_for @conn, "/courses", [class: "course-form form-inline", as: :course], fn f -> %>
<td class="id"><%= course.code %></td>
<td class="id"><%= course.title %></td>
<td class="id"><%= course.credits %></td>
<td class="id"><button type="submit" class= "btn btn-primary ">Select</button> </td>

<%= hidden_input f, :course_id, value: course.id %>
         </tr>
           <% end %>
         <% end %>
       </tbody>
    </table>

<div class="course-count"></div>

</div>
</div>
</div>

lib/registration_web/templates/course/view.html.eex
<div class="column main-pane">


  <div class= "content-pane">
<div class="title-text"> Selected Courses </div>
<table class="table table-striped table-hover trans-table column col-11 col-mx-auto">
      <thead>
        <tr>
          <th>Code</th>
          <th>Title</th>
          <th>Credits</th>
           <th>Action</th>
        </tr>
      </thead>
      <tbody>
<%= for course <- @student.courses do %>
         <tr>

<td class="id"><%= course.code %></td>
<td class="id"><%= course.title %></td>
<td class="id"><%= course.credits %></td>
<td class="id"> <%= link "Delete", to: Routes.course_path(@conn, :delete, course), class: "btn btn-primary", method: :delete, data: [confirm: "Are you sure?"] %></td>


         </tr>
           
         <% end %>
       </tbody>
    </table>

<div class="course-count"></div>
 
<span class="btn btn-primary" style="margin-top:20px"><a style="color:white" href="/courses"> Add More Courses</a></span>
</div>
</div>

lib/registration_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Portal · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
<!--<%= render "app_nav.html", conn: @conn, student: @current_student %> -->
    <main role="main" class="jj">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <div class= "title-pane">
        <%= if @current_student do %>
        <div class= "header-text">Welcome back, <b><%=@current_student.name %></b></div>
        <% else %>
         <div class= "header-text">Hi There  <b></b></div>
        <% end %>
       </div>
           
   <div class="grid-container columns">
        <div class=" side-pane column">
        <div class="icon-container">
        <%= if @current_student do %>
         <button class="bt" id= "b3" onclick="location.href='/'"> My Profile</button>
            <button class="bt" id= "b1" style="background-color:#5755d9 ;color:white" onclick="location.href='/courses'">  Registration </button>
            <button class="bt" id= "b2" onclick="location.href='/papers'"> Submission</button>
           <% else %>
             <button class="bt" id= "b1" style="background-color:#5755d9 ;color:white" onclick="location.href='/login'">Login</button>
            <button class="bt" id= "b2" onclick="location.href='/signup'"> Sign Up </button>
            <% end %>


         </div>
      </div>
     
     
     <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    
		
  </body>
</html>

lib/registration_web/templates/page/index.html.eex
<div class="column main-pane">


  <div class= "content-pane">
<div class="title-text">My Profile </div>

<div class="columns">
<div class="column col-2 field1">Name: </div><div class="column col-10 fields"><%= @current_student.name %></div>
<div class="column col-2 field1">Mat No: </div><div class="column col-10 fields"><%= @current_student.matno %></div>
<div class="column col-2 field1">Department: </div><div class="column col-10 fields"><%= @current_student.department%></div>
<div class="column col-2 field1">Email: </div><div class="column col-10 fields"><%= @current_student.email %></div>
<div class="column col-2 field1">Level: </div><div class="column col-10 fields"><%= @current_student.level %></div>
<div class="column col-2 field1">Hall: </div><div class="column col-10 fields"><%= @current_student.hall %></div>


<div class="column col-2 field1">Courses: </div><div class="column col-10 field course_fields" ><%= @current_student.courses|>Enum.map(&(&1.title)) |> Enum.join(", ") %></div>

</div>
<span class="btn btn-primary" style="margin-top:20px"><a style="color:white" href= "/courses"> Add Courses</a></span>

  </div>
  </div>

lib/registration_web/templates/paper/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
<div class= "columns">
<div class="column col-2 field "><%= label f, :subject %> </div>
<div class="column col-10 field"> <%= text_input f, :subject %></div>
  <%= error_tag f, :subject %>
 



  <div class="column col-2 field "><%= label f, :department %></div>
  
 <div class="column col-10 field"> <%= select f, :department, ["Chemistry"] %></div>
  <%= error_tag f, :department %>

  <div class="column col-2 field "><%= label f, :term %></div>
  <div class="column col-10 field"><%= text_input f, :term %></div>
  <%= error_tag f, :term %>
 
  <div class="column col-2 field "> <%= label f, :body %></div>
  <div class="column col-10 field"><%= textarea f, :body %></div>
  <%= error_tag f, :body %>
  

  <div class="column col-12" >
   <button type="submit" class= "btn btn-primary ">Send</button>
   
   </div>
  
   </div>
<% end %>

lib/registration_web/templates/paper/index.html.eex
<div class="column main-pane">


  <div class= "content-pane">

<div class="title-text">Term Papers</div>



<table  class="table table-striped table-hover trans-table column col-11 col-mx-auto">
  <thead>
    <tr>
  
      <th class="subject">Subject</th>
      
     
      <th class="action">Action</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for paper <- @papers do %>
    <tr>
   
      <td><%= paper.subject %></td>
      
      <td> <%= link "Show", to: Routes.paper_path(@conn, :show, paper) %></td>
     

      <td>
      
      </td>
    </tr>
<% end %>
  </tbody>
</table>


<span class="btn btn-primary" style="margin-top:20px; margin-left:52px"><a style="color:white" href= "/papers/new"> Add A Term Paper</a></span>
</div>
</div>

lib/registration_web/templates/paper/new.html.eex
<div class="column main-pane">


  <div class= "content-pane">




<div class="title-text">New Paper</div>

<%= render "form.html", Map.put(assigns, :action, Routes.paper_path(@conn, :create)) %>

lib/registration_web/templates/paper/show.html.eex
<div class="column main-pane">


  <div class= "content-pane">

<div class="title-text">Show Paper</div>



  <div>
    <strong>Subject:</strong>
    <p> <%= @paper.subject %></p>
  </div>

 

  <div>
    <strong>Department:</strong>
     <p><%= @paper.department %></p>
  </div>

  <div>
    <strong>Term:</strong>
    <p><%= @paper.term %></p>
  </div>
   <div>
    <strong>Body:</strong>
     <p><%= @paper.body %></p>
  </div>






<span class="btn btn-primary" style="margin-top:20px; margin-left:2px"><a style="color:white" href= "/papers"> Back</a></span>
</div>
</div>

lib/registration_web/templates/session/new.html.eex
<div class="column main-pane">


  <div class= "content-pane_login">

<div class="row redact-form">
<div class="col-9" style="margin: 20px 10px 0px 40px">
<div class="title-text">Login</div>
<%= form_for @conn, Routes.session_path(@conn, :create), [as: :session, id: "login-form"], fn f -> %> 

<div class="form-group redact">
<%= text_input f, :matno, placeholder: "matno", class:
"form-control" %>
</div>
<div class="form-group redact">
<%= password_input f, :password, placeholder: "Password",
class: "form-control" %>
</div>
<%= submit "Log in", class: "btn btn-primary redact-btn" %>
<% end %>
</div>
</div></div>
</div>

lib/registration_web/templates/signup/new.html.eex
<div class="column main-pane">


  <div class= "content-pane-2">
<div class="title-text"> Register account </div>
<div class="columns redact-form-2">
<%= form_for @changeset, Routes.signup_path(@conn, :create), [as:
:student, id: "registration-form"], fn f -> %>
<div class="form-group column col-10">
<%= label f, :name, class: "control-label" %>
<%= text_input f, :name, class: "form-control" %>
<%= error_tag f, :name %>
</div>




<div class="form-group column col-10">
<%= label f, :matno, class: "control-label" %>
<%= text_input f, :matno, class: "form-control" %>
<%= error_tag f, :matno %>
</div>
<div class="form-group column col-10">
 <label class="form-label" for="student_department">Department</label>
<select id = "student_department" name="student[department]" class="selector">
<option value="Chemistry"> Chemistry </option>
</select>
</div>



<div class="form-group column col-10">
<%= label f, :level, class: "control-label" %>
<%= text_input f, :level, class: "form-control" %>
<%= error_tag f, :level %>
</div>

<div class="form-group column col-10">
<%= label f, :hall, class: "control-label" %>
<%= text_input f, :hall, class: "form-control" %>
<%= error_tag f, :hall %>
</div>



<div class="form-group column col-10"> 
<%= label f, :password, class: "control-label" %>
<%= password_input f, :password, placeholder: "Password",
class: "form-control" %>
<%= error_tag f, :password %>
</div>
<div class="form-group column col-10"> 
 <button type="submit" class= "btn btn-primary reg_btn" >Send</button>
 </div>
<% end %>
</div>
</div>